Website/Models/Request.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Website.Models
{
    public class Request
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string status { get; set; }
        public DateTime DateTime { get; set; }
        public string Message { get; set; }
    }

    public class Status
    {
        public string Received { get => "Получена"; }
        public string InWork { get => "В работе"; }
        public string Completed { get => "Выполнена"; }
        public string Rejected { get => "Отклонена"; }
        public string Canceled { get => "Отменена"; }
     }
}

Website/Controllers/SiteController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Website.Data;
using Website.Interfaces;
using Website.Models;

namespace Website.Controllers
{
    public class SiteController : Controller
    {
        private IRequestsData _requestsData;
        public SiteController(IRequestsData requestsData)
        {
            _requestsData = requestsData;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Projects()
        {
            return View();
        }

        public IActionResult Sb()
        {
            return View();
        }

        public IActionResult Mr()
        {
            return View();
        }

        public IActionResult Services()
        {
            return View();
        }
        public IActionResult Blog()
        {
            return View();
        }

        public IActionResult C_page1()
        {
            return View();
        }

        public IActionResult C_page2()
        {
            return View();
        }

        public IActionResult C_page3()
        {
            return View();
        }

        public IActionResult C_page4()
        {
            return View();
        }

        public IActionResult Contacts()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddRequest(string name, string email, string message)
        {
            
            var request = new Request()
            {
                Name = name,
                Email = email,
                status = new Status().Received,
                DateTime = DateTime.Now,
                Message = message
            };
            _requestsData.AddRequest(request);
            return Redirect("Index");
        }
    }
}

Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]Вебсайт</title>
    <link rel="stylesheet" href="/css/reset.css" />
    <link rel="stylesheet" href="~/css/style.css" />
</head>
<body>
    <div class="header">
        <div class="none"></div>
        <div class="nav">
            <ul class="items">
                <li><a asp-controller="Site" asp-action="Index">Главная</a></li>
                <li><a asp-controller="Site" asp-action="Projects">Проекты</a></li>
                <li><a asp-controller="Site" asp-action="Services">Услуги</a></li>
                <li><a asp-controller="Site" asp-action="Blog">Блог</a></li>
                <li><a asp-controller="Site" asp-action="Contacts">Контакты</a></li>
            </ul>
            <div class="text">
                "РАСШИРЯЕМ ВОЗМОЖНОСТИ"
            </div>
        </div>
    </div>
    <div>
        @RenderBody()
    </div>
    <footer>
        <div class="footer">Website</div>
    </footer>
</body>
</html>

Website/Views/Site/Blog.cshtml
@model Website.Views.Site.BlogModel
@{
}

<body class="container__page-projects">
    <div class="projects__block">
        <div class="container__projects-header">
            <h1 class="projects__header-text">Блог</h1>
        </div>

        <div class="blog">
            <div>
                <div class="blog__card-data">5 апреля 2020</div>
                <a class="blog__card" asp-controller="Site" asp-action="C_page1" target="_blank">
                    <div class="card__pucture1"></div>
                    <p class="card__title">
                        1C: Производственная безопасность
                    </p>
                    <p class="card__text">
                        Решения обеспечивают автоматизацию процессов учета,
                        планирования, контроля и формирования аналитической
                        отчетности в соответствии с требованиями законодательства РФ
                    </p>
                </a>
            </div>
            <div>
                <div class="blog__card-data">1 апреля 2020</div>
                <a class="blog__card" asp-controller="Site" asp-action="C_page2" target="_blank">
                    <div class="card__pucture2"></div>
                    <p class="card__title">
                        1С: Производственная безопасность
                    </p>
                    <p class="card__text">
                        Решения обеспечивают автоматизацию процессов учета,
                        планирования, контроля и формирования аналитической
                        отчетности в соответствии с требованиями законодательства РФ
                    </p>
                </a>
            </div>
            <div>
                <div class="blog__card-data">30 марта 2020</div>
                <a class="blog__card" asp-controller="Site" asp-action="C_page3" target="_blank">
                    <div class="card__pucture3"></div>
                    <p class="card__title">
                        1С: Производственная безопасность
                    </p>
                    <p class="card__text">
                        Решения обеспечивают автоматизацию процессов учета,
                        планирования, контроля и формирования аналитической
                        отчетности в соответствии с требованиями законодательства РФ
                    </p>
                </a>
            </div>
            <div>
                <div class="blog__card-data">28 марта 2020</div>
                <a class="blog__card" asp-controller="Site" asp-action="C_page4" target="_blank">
                    <div class="card__pucture4"></div>
                    <p class="card__title">
                        1С: Производственная безопасность
                    </p>
                    <p class="card__text">
                        Решения обеспечивают автоматизацию процессов учета,
                        планирования, контроля и формирования аналитической
                        отчетности в соответствии с требованиями законодательства РФ
                    </p>
                </a>
            </div>            
        </div>
    </div>
</body>

Website/Views/Site/C_page1.cshtml
@model Website.Views.Site.C_page1Model
@{
}

<body class="container__page-projects">
    <div class="projects__block">
        <div class="container__projects-header">
            <h1 class="projects__header-text">1С: Производственная безопасность</h1>
        </div>
        <div>
            <div class="blog__card-data">5 апреля 2020</div>
            <div class="blog__page">
                <div class="page__card-pucture1"></div>
                <div>
                    <p class="blog__page-text">
                        Решения обеспечивают автоматизацию процессов учета,
                        планирования, контроля и формирования аналитической
                        отчетности в соответствии с требованиями законодательства РФ,
                        отраслевой и корпоративной специфики
                    </p>
                </div>
            </div>            
        </div>        
    </div>
</body>

Website/Views/Site/C_page2.cshtml
@model Website.Views.Site.C_page2Model
@{
}

<body class="container__page-projects">
    <div class="projects__block">
        <div class="container__projects-header">
            <h1 class="projects__header-text">1С: Производственная безопасность</h1>
        </div>
        <div>
            <div class="blog__card-data">1 апреля 2020</div>
            <div class="blog__page">
                <div class="page__card-pucture2"></div>
                <div>
                    <p class="blog__page-text">
                        Решения обеспечивают автоматизацию процессов учета,
                        планирования, контроля и формирования аналитической
                        отчетности в соответствии с требованиями законодательства РФ,
                        отраслевой и корпоративной специфики
                    </p>
                </div>
            </div>
        </div>
    </div>
</body>

Website/Views/Site/C_page3.cshtml
@model Website.Views.Site.C_page3Model
@{
}

<body class="container__page-projects">
    <div class="projects__block">
        <div class="container__projects-header">
            <h1 class="projects__header-text">1С: Производственная безопасность</h1>
        </div>
        <div>
            <div class="blog__card-data">30 марта 2020</div>
            <div class="blog__page">
                <div class="page__card-pucture3"></div>
                <div>
                    <p class="blog__page-text">
                        Решения обеспечивают автоматизацию процессов учета,
                        планирования, контроля и формирования аналитической
                        отчетности в соответствии с требованиями законодательства РФ,
                        отраслевой и корпоративной специфики
                    </p>
                </div>
            </div>
        </div>
    </div>
</body>

Website/Views/Site/C_page4.cshtml
@model Website.Views.Site.C_page4Model
@{
}

<body class="container__page-projects">
    <div class="projects__block">
        <div class="container__projects-header">
            <h1 class="projects__header-text">1С: Производственная безопасность</h1>
        </div>
        <div>
            <div class="blog__card-data">28 марта 2020</div>
            <div class="blog__page">
                <div class="page__card-pucture4"></div>
                <div>
                    <p class="blog__page-text">
                        Решения обеспечивают автоматизацию процессов учета,
                        планирования, контроля и формирования аналитической
                        отчетности в соответствии с требованиями законодательства РФ,
                        отраслевой и корпоративной специфики
                    </p>
                </div>
            </div>
        </div>
    </div>
</body>

Website/Views/Site/Contacts.cshtml
@model Website.Views.Site.ContactsModel
@{
}

<body class="container__page-projects">
    <div class="projects__block">
        <div class="container__projects-header">
            <h1 class="projects__header-text">Контакты</h1>
        </div>
        <div class="contacts__container">
            <div class="contacts">
                <a class="contacts__tel" href="tel:89999999999">Телефон: 8(999)999-99-99</a>
                <p>Адрес: Республика Коми г. Печора</p>
            </div>
            <div class="map"></div>
        </div>
    </div>
</body>

Website/Views/Site/Index.cshtml
@model Website.Controllers.SiteController
@{
}

<body class="container__page-index">
    <div class="background">
        <p class="background__text">
            Оставить заявку
        </p>
    </div>
    <div class="container">
        <div class="field">
            <div class="field__text">
                Оставить заявку или задать вопрос
            </div>
            <form action="~/Site/AddRequest" method="post">
                <div class="field__user-data">
                    <div class="field__name">
                        <h3>ФИО</h3>
                        <input name="Name" style="height:20px; width:400px; font-size: 15px" id="Name"/>
                    </div>
                    <div class="field__email">
                        <h3>Email</h3>
                        <input name="Email" style="height: 20px; width: 400px; font-size: 15px" id="Email"/>
                    </div>
                </div>
                <div class="field__message">
                    <h3>Текст сообщения</h3>
                    <input name="Message" style="height: 50px; width: 830px; font-size: 15px" id="Message"/>
                </div>
                <button class="btn" type="submit" disabled>Отправить</button>
            </form>            
        </div>
    </div>
    <script src="~/js/scripts.js"></script>
</body>

Website/Views/Site/Mr.cshtml
@model Website.Views.Site.MrModel
@{
}

<body class="container__page-projects">
    <div class="projects__block">
        <table>
            <tr>
                <td class="sb__td-headertext"><h1 class="projects__header-text">Управление кадрами и расчет зарплаты</h1></td>
                <td class="sb__td-headericon"><div class="mr__icon"></div></td>
            </tr>
            <tr>
                <td class="sb__table-text">
                    <pre>
                    </pre>
                </td>
            </tr>
        </table>
    </div>
</body>

Website/Views/Site/Projects.cshtml
@model Website.Views.Site.ProjectsModel
@{
}

<body class="container__page-projects">
    <div class="projects__block">
        <div class="container__projects-header">
            <h1 class="projects__header-text">Проекты</h1>
        </div>
        <div class="container__page-projects">
            <ul class="container__projects-pictures">
                <li>
                    <div class="picture__border1">
                        <a asp-controller="Site" asp-action="Sb"></a>
                    </div>
                </li>
                <li>
                    <div class="picture__border2">
                        <a asp-controller="Site" asp-action="Mr"></a>
                    </div>
                </li>
                <li>
                    <div class="picture__border3">
                        <a asp-controller="" asp-action=""></a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</body>

Website/Views/Site/Sb.cshtml
@model Website.Views.Site.sbModel
@{
}

<body class="container__page-projects">
    <div class="projects__block">
        <table>
            <tr>
                <td class="sb__td-headertext"><h1 class="projects__header-text">Обработка кредитных заявок в режиме онлайн</h1></td>
                <td class="sb__td-headericon"><div class="sb__icon"></div></td>
            </tr>
            <tr>
                <td class="sb__table-text">
                    <pre>
Для реализации проекта была выбрана платформа IBM WebSphere, поскольку входящий в нее инструментарий BPM
оказался наиболее подходящим для автоматизации уникальных бизнес-процессов заказчика.

В качестве пилотного процесса был автоматизирован процесс "Управление маркетинговыми коммуникациями",
что позволило банку протестировать возможности платформы IBM BPM.
                    </pre>
                </td>
            </tr>
        </table>
    </div>
    





    
</body>

Website/Views/Site/Services.cshtml
@model Website.Views.Site.ServicesModel
@{
}

<body class="container__page-projects">
    <div class="projects__block">
        <div class="container__projects-header">
            <h1 class="projects__header-text">Что мы можем сделать</h1>
        </div>
        <div class="spoiler">
            <details class="spoiler__item">
                <summary class="spoiler__title">Импортозамещение</summary>
                <p class="spoiler__text">
                    В ряде работ было показано, что в целом импортозамещение способствует значительному росту
                    отечественного производства, создаются новые рабочие места, однако в долгосрочной
                    перспективе в странах Латинской Америки и Южной Америки наблюдалось снижение темпов
                    экономического роста.
                </p>
            </details>
            <details class="spoiler__item">
                <summary class="spoiler__title">Цифровые решения</summary>
                <p class="spoiler__text">
                    Компания "Цифровые решения"
                    Мы постоянно совершенствуем наши продукты и предоставляем высокоэффективные решения для
                    компаний из разных отраслей, разрабатывая проекты под индивидуальные особенности вашего бизнеса.
                </p>
            </details>
        </div>
    </div>
</body>